### ISSUE TITLE
"Invalid arguments (on pointer constructor)"-error after adding content to a PenpotPath

### ISSUE THREAD

**Issue by girafic** [penpot/penpot-plugins#132]
After adding content to a PenpotPath I get an error with the message "Invalid arguments (on pointer constructor)"

```
const path = penpot.createPath()
path.content = [
  { command: "M", params: { x: 0, y: 0 } },
  { command: "L", params: { x: 200, y: 200 }},
];
```

**Comment by juanfran** [comment]
Fixed in the Penpot develop branch https://github.com/penpot/penpot/pull/4992. Thanks!
