### ISSUE TITLE
insertChild and appendChild always creates shapes on RootFrame

### ISSUE THREAD

**Issue by girafic** [penpot/penpot-plugins#155]
```
const elementParent = selectedElement?.parent;
...
elementParent.insertChild(0, penpot.createRectangle());
elementParent.appendChild(penpot.createEllipse());
...
```
When adding new rectangles or ellipses to the parent frame of a selected element, the methods `insertChild` and `appendChild` will add the new elements to the `Root Frame`, not to parent frame. 

<img width="973" alt="grafik" src="https://github.com/user-attachments/assets/e845c860-8742-445c-aff7-6ffa749b47ba">

-->

<img width="962" alt="grafik" src="https://github.com/user-attachments/assets/ea864bb8-3677-4c7e-a9a3-b0bda55fb214">

**Comment by Alotor** [comment]
Thanks for the report. The problem was in the `parent` retrieval wasn't setting well the permissions. I've fixed and we be in `develop` soon.

**Comment by girafic** [comment]
> Thanks for the report. The problem was in the `parent` retrieval wasn't setting well the permissions. I've fixed and we be in `develop` soon.

Would be nice if you could also deploy the changes to early.penpot.dev 😊
